
[__meta]
	version = 12

[general]

	[general.online_status]
		show_essential_indicator_on_tab = true
		show_essential_indicator_on_nametags = true

	[general.general]
		streamer_mode = false
		modcore_warning = true
		timestamps_format = 0
		replace_window_title = true

	[general.experience]
		enable_essential = true
		essential_menu_layout = 0
		closer_placement_of_minimal_essential_menu = true
		use_vanilla_button_texture = false
		darken_re-textured_menu_buttons = false
		quick_action_bar = true

[privacy]

	[privacy.general]
		display_current_server = false
		friend_privacy_settings = 0

[notifications]

	[notifications.warnings]
		link_opening_warning = true

	[notifications.general]
		online_friend_alert = true
		disable_all_notifications = false
		message_notifications = true
		group_message_notifications = true
		message_sound = true
		update_notifications = false
		host_world_ip_warning = true
		screenshot_toast_duration = 1

[quality_of_life]

	[quality_of_life.zoom]
		smooth_camera_when_zoomed = true
		smooth_zoom_animation = false
		toggle_to_zoom = false

	[quality_of_life.general]
		auto_refresh_session = true

	[quality_of_life.fullscreen]
		windowed_fullscreen = false

	[quality_of_life.discord_integration]
		set_activity_status_on_discord = false
		allow_ask_to_join = true
		show_username_and_avatar = true
		show_current_server = false

	[quality_of_life.screenshots]
		essential_screenshots = true
		screenshot_sounds = true
		vanilla_screenshot_message = false
		"screenshot_quick_action_#1_-_top_left" = 5
		"screenshot_quick_action_#2_-_top_right" = 2
		"screenshot_quick_action_#3_-_bottom_left" = 0
		"screenshot_quick_action_#4_-_bottom_right" = 4
		post_screenshot_action = 0

	[quality_of_life.accessibility]
		enlarge_chat_metadata = false

	[quality_of_life.nameplate]
		show_my_nameplate_in_third-person = false

[cosmetics]

	[cosmetics.general]
		disable_cosmetics = false
		hide_cosmetics_on_server_skins = false
		disable_cosmetics_in_inventory = false
		"cosmetic_&_armor_conflict_-_on_myself" = 0
		"cosmetic_&_armor_conflict_-_on_others" = 0
		hide_cosmetic_particles_in_first_person = false

[hidden]
	previously_launched_with_container = 1
	play_emote_sounds_in_wardrobe = true

	[hidden.hidden]
		emote_perspective = 1
		screenshotbrowseritemsperrow = 3
		coinsselectedcurrency = "USD"
		coinspurchasecreatorcode = "__default__"
		spspinnedgamerules = ""
		showemotepagekeybindbanner = true

[emotes]

	[emotes.general]
		play_emotes_in_third_person_view = true
		emote_preview = false
		disable_emotes = false
		allow_emote_sounds = 0

