
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1134605
	#The name of the modpack
	modpackName = "Beyond Depth"
	#The version of the modpack
	modpackVersion = "Ver11.3.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

