
["Falling Penalty"]
	#This sets wheter or not you get slowed down if falling from too high
	"Falling Penalty" = true

["HayBale negates fall damage"]
	#This determines if landing on a Haybale block negates fall damage.
	"HayBale negates fall damage" = true

["Animation Triggers set on/off:"]
	"Fall Animation" = false
	"Landing Animation" = true
	"High Fall Landing Animation" = true
	"Jumping Animation" = false
	"CannonBall Animation" = false
	#Setting Diving Animation to false will disable rolling animation.
	"Diving Animation" = false
	"Hay Bale Animation" = true

