
[ShieldList]
	#
	#List of items to considered as shields, any item with right-click functionality will theoretically work
	#Automatically populated with items that have parrying stats set by active datapacks
	shieldList = ["shieldexp:wooden_shield", "shieldexp:griefer_shield", "shieldexp:iron_shield", "shieldexp:netherite_shield", "alexsmobs:shield_of_the_deep", "minecraft:shield", "shieldexp:golden_shield", "shieldexp:diamond_shield", "shieldexp:paragon_shield", "nethers_exoticism:rambutan_shield", "bygonenether:gilded_netherite_shield", "endermanoverhaul:corrupted_shield", "blazegear:brimsteel_shield", "voidscape:voidic_crystal_shield", "cataclysm:bulwark_of_the_flame", "cataclysm:black_steel_targe", "undergarden:cloggrum_shield", "artifacts:umbrella", "legendary_monsters:spiky_shield", "legendary_monsters:frostbitten_shield", "legendary_monsters:dinosaur_bone_shield", "legendary_monsters:shulker_shield", "cataclysm:azure_sea_shield", "stalwart_dungeons:tungsten_shield", "stalwart_dungeons:chorundum_shield", "stalwart_dungeons:warted_tungsten_shield"]
	#
	#List of items to not consider as shields, even if they have stats set by a datapack
	shieldBlacklist = []

[Modifiers]
	#
	#Disable the cooldown when the player lowers their shield
	noLoweringCooldown = false
	#
	#Disable putting shields on cooldown at all
	noCooldown = false
	#
	#Make all shields have vanilla movement speed
	noSpeedModifier = false
	#
	#Make shields only block partial damage from explosions when not parrying
	harderExplosions = false
	#
	#Double the parry window for a more relaxed experience
	lenientParryMode = false
	#
	#Double the shield stamina for a more relaxed experience
	lenientStaminaMode = false

