[General]
	#
	############################################
	#Enable this to show the cosmetic button in the main menu and pause screen
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Show Cosmetic Button" = true
	#
	############################################
	#Enable this to show the unionlib config button in the main menu and pause screen
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Show Config Button" = true
[Tooltips]
	#
	############################################
	#Sets the color of the tag tooltip
	#-------------------------------------------
	#Default: 5263440
	#-------------------------------------------
	#Range: -2147483648 ~ 2147483647
	"Integer: Tag Color" = 5263440
	#
	############################################
	#Enable this to have the tags for certain items
	#-------------------------------------------
	#Default: false
	#-------------------------------------------
	"Boolean: Show Tags" = false
[Menus]
	#
	############################################
	#This determines how long text will stay in an overflow before it resets
	#Measured in ticks
	#-------------------------------------------
	#Default: 40
	#-------------------------------------------
	#Range: 1 ~ 100
	"Integer: Text Overflow Reset Time" = 40
	#
	############################################
	#This determines how fast text scrolls if there is an overflow
	#Measured in ticks
	#-------------------------------------------
	#Default: 20
	#-------------------------------------------
	#Range: 1 ~ 100
	"Integer: Text Overflow Scroll Speed" = 20

