
[blocks]
	Sawmill = true
	"Wooden boards" = true
	"Wooden bookshelves" = true
	"Wooden ladders" = true
	"Wooden beehives" = false
	"Wooden chests" = true
	"Leaf piles" = false

[generation]
	#If variant bookshelves replace bookshelves in Villages
	"Wooden bookshelves in Villages" = false
	#If variant ladders replace ladders in Villages
	"Wooden ladders in Villages" = false
	#If variant chests replace chests in Villages
	"Wooden chests in Villages" = false

