ServerEvents.tags('item', event => {
    // Remove specific materials from the #minecraft:trim_materials tag                                                                                                                                                                                                                 made by blueversal                                                                                                                                                                              beyond depth
    event.remove('minecraft:trim_materials', 'cataclysm:witherite_ingot')
    event.remove('minecraft:trim_materials', 'cataclysm:ancient_metal_ingot')
    event.remove('minecraft:trim_materials', 'cataclysm:cursium_ingot')
    event.remove('minecraft:trim_materials', 'cataclysm:ignitium_ingot')
    event.remove('minecraft:trim_materials', 'palegardenbackport:resin_clump')
    event.remove('minecraft:trim_materials', 'undergarden:froststeel_ingot')
    event.remove('minecraft:trim_materials', 'undergarden:forgotten_ingot')
    event.remove('minecraft:trim_materials', 'undergarden:cloggrum_ingot')
    event.remove('minecraft:trim_materials', 'rubinated_nether:ruby')
    event.remove('minecraft:trim_materials', 'undergarden:utherium_crystal')
    event.remove('minecraft:trim_materials', 'undergarden:regalium_crystal')
    event.remove('minecraft:trim_materials', 'upgrade_aquatic:thrasher_tooth')    
    event.remove('minecraft:trimmable_armor', 'additionaladditions:gilded_netherite_helmet')
    event.remove('minecraft:trimmable_armor', 'additionaladditions:gilded_netherite_chestplate')
    event.remove('minecraft:trimmable_armor', 'additionaladditions:gilded_netherite_leggings')
    event.remove('minecraft:trimmable_armor', 'additionaladditions:gilded_netherite_boots')
    event.remove('minecraft:trimmable_armor', 'biomemakeover:cladded_helmet')
    event.remove('minecraft:trimmable_armor', 'biomemakeover:cladded_chestplate')
    event.remove('minecraft:trimmable_armor', 'biomemakeover:cladded_leggings')
    event.remove('minecraft:trimmable_armor', 'biomemakeover:cladded_boots')
  })